---
title: "Manuscript Analyses"
output: html_notebook
---

```{r}
library(tidyverse)
library(lmerTest)
library(ggpubr)
library(ggh4x)
library(patchwork)
```

# Exp 1

```{r}
exp1_colnames <- c("source", "variable", "word", "n", "m", "sd")

scope <- read_csv("data/manuscript/expt1msd/scope.csv", col_names = exp1_colnames)
gpt35 <- read_csv("data/manuscript/expt1msd/expt1gpt35.csv", col_names = exp1_colnames)
gpt4 <- read_csv("data/manuscript/expt1msd/expt1gpt4.csv", col_names = exp1_colnames)
gpt4o <- read_csv("data/manuscript/expt1msd/expt1gpt4o.csv", col_names = exp1_colnames)
gem15 <- read_csv("data/manuscript/expt1msd/expt1gem15.csv", col_names = exp1_colnames)

exp1_data <- rbind(scope, gpt35, gpt4, gpt4o, gem15)
```

## Means

```{r}
exp1_m_data <- exp1_data %>%
  select(!c(n, sd)) %>%
  rename("value" = m)
```

```{r}
scope_data <- exp1_m_data %>%
  filter(source == "scope") %>%
  rename("scope" = value) %>%
  select(!source)

model_data <- exp1_m_data %>%
  filter(source != "scope") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!source)

exp1_m_df <- left_join(model_data, scope_data) %>%
  mutate(model = factor(model, levels = c("gpt35", "gpt4", "gpt4o", "gem15")),
         variable = factor(variable)) %>%
  group_by(model, variable) %>%
  mutate(z_scope = as.numeric(scale(scope)),
         z_value = as.numeric(scale(value)))
```

```{r}
facet_labels <- c(
  "aoa" = "AoA Rating",
  "arousal" = "Arousal",
  "conc" = "Concreteness",
  "dom" = "Dominance",
  "fam" = "Familiarity",
  "gender" = "Gender Association",
  "humor" = "Humorousness",
  "image" = "Imageability",
  "size" = "Semantic Size",
  "social" = "Socialness",
  "valence" = "Valence"
)

ggplot(exp1_m_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")), aes(x=value, y=scope, color=model, fill=model)) +
  facet_wrap(~variable, labeller = labeller(variable = facet_labels), scales = "free") +
  ggh4x::facetted_pos_scales(
    x = list(
    variable == "aoa" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7),
    variable == "conc" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7),
    variable == "fam" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7),
    variable == "gender" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7),
    variable == "image" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7),
    variable == "size" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7),
    variable == "arousal" ~ scale_x_continuous(limits = c(1,9), n.breaks = 9),
    variable == "dom" ~ scale_x_continuous(limits = c(1,9), n.breaks = 9),
    variable == "valence" ~ scale_x_continuous(limits = c(1,9), n.breaks = 9),
    variable == "humor" ~ scale_x_continuous(limits = c(1,5), n.breaks = 5),
    variable == "social" ~ scale_x_continuous(limits = c(1,7), n.breaks = 7)
  ), y = list(
    variable == "aoa" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7),
    variable == "conc" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7),
    variable == "fam" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7),
    variable == "gender" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7),
    variable == "image" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7),
    variable == "size" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7),
    variable == "arousal" ~ scale_y_continuous(limits = c(1,9), n.breaks = 9),
    variable == "dom" ~ scale_y_continuous(limits = c(1,9), n.breaks = 9),
    variable == "valence" ~ scale_y_continuous(limits = c(1,9), n.breaks = 9),
    variable == "humor" ~ scale_y_continuous(limits = c(1,5), n.breaks = 5),
    variable == "social" ~ scale_y_continuous(limits = c(1,7), n.breaks = 7)
  )) +
  geom_point(alpha=0.15, size=1, shape=1) +
  geom_smooth(method="lm", size=0.5) +
  stat_cor(aes(label = ..r.label..), method = "pearson", digits = 2, show.legend = F, size = 2) +
  labs(x = "Model", y = "Human", color ="Model", fill = "Model") +
  scale_color_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  scale_fill_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  theme_bw() + 
  theme(legend.position = c(0.89,0.15),
        legend.key.size = unit(0.5, "cm"),
        strip.text.x = element_text(margin = margin(t = 2, b = 2)),
        strip.text = element_text(size = 8),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        # panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

# ggsave("figures/manuscript/exp1_means.png", width = 7.29, height = 4.5)
```

```{r}
m1.1 <- lmer(z_scope ~ z_value * model + (1|word), data = exp1_m_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))
summary(m1.1)
```

```{r}
m1.2_main <- lmer(z_scope ~ z_value + variable + (1|word), data = exp1_m_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))
m1.2_intr <- lmer(z_scope ~ z_value * variable + (1|word), data = exp1_m_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))

anova(m1.2_main, m1.2_intr)
```

## SDs

```{r}
exp1_sd_data <- exp1_data %>%
  select(!c(n, m)) %>%
  rename("value" = sd)
```

```{r}
scope_data <- exp1_sd_data %>%
  filter(source == "scope") %>%
  rename("scope" = value) %>%
  select(!source)

model_data <- exp1_sd_data %>%
  filter(source != "scope") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!source)

exp1_sd_df <- left_join(model_data, scope_data) %>%
  mutate(model = factor(model, levels = c("gpt35", "gpt4", "gpt4o", "gem15")),
         variable = factor(variable)) %>%
  group_by(model, variable) %>%
  mutate(z_scope = as.numeric(scale(scope)),
         z_value = as.numeric(scale(value)))
```

```{r}
facet_labels <- c(
  "aoa" = "AoA Rating",
  "arousal" = "Arousal",
  "conc" = "Concreteness",
  "dom" = "Dominance",
  "fam" = "Familiarity",
  "gender" = "Gender Association",
  "humor" = "Humorousness",
  "image" = "Imageability",
  "size" = "Semantic Size",
  "social" = "Socialness",
  "valence" = "Valence"
)

sd_limits_max <- exp1_sd_df %>%
  group_by(variable) %>%
  summarize(max_scope = max(scope), max_value = max(value), min_scope = min(scope), min_value = min(value)) %>%
  group_by(variable) %>%
  summarize(max = max(max_scope, max_value), min = min(min_scope, min_value))

ggplot(exp1_sd_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")),
       aes(x=value, y=scope, color=model, fill=model)) +
  facet_wrap(~variable, labeller = labeller(variable = facet_labels), scale = "free") +
  ggh4x::facetted_pos_scales(
   x = list(
   variable == "aoa" ~ scale_x_continuous(limits = c(0,1.708000)),
   variable == "conc" ~ scale_x_continuous(limits = c(0,2.267000)),
   variable == "fam" ~ scale_x_continuous(limits = c(0,2.147000)),
   variable == "gender" ~ scale_x_continuous(limits = c(0,2.551448)),
   variable == "image" ~ scale_x_continuous(limits = c(0,2.198000)),
   variable == "size" ~ scale_x_continuous(limits = c(0,2.059000)),
   variable == "arousal" ~ scale_x_continuous(limits = c(0,3.157000)),
   variable == "dom" ~ scale_x_continuous(limits = c(0,3.181000)),
   variable == "valence" ~ scale_x_continuous(limits = c(0,2.461000)),
   variable == "humor" ~ scale_x_continuous(limits = c(0,1.609114)),
   variable == "social" ~ scale_x_continuous(limits = c(0,2.492847))
  ), y = list(
   variable == "aoa" ~ scale_y_continuous(limits = c(0,1.708000)),
   variable == "conc" ~ scale_y_continuous(limits = c(0,2.267000)),
   variable == "fam" ~ scale_y_continuous(limits = c(0,2.147000)),
   variable == "gender" ~ scale_y_continuous(limits = c(0,2.551448)),
   variable == "image" ~ scale_y_continuous(limits = c(0,2.198000)),
   variable == "size" ~ scale_y_continuous(limits = c(0,2.059000)),
   variable == "arousal" ~ scale_y_continuous(limits = c(0,3.157000)),
   variable == "dom" ~ scale_y_continuous(limits = c(0,3.181000)),
   variable == "valence" ~ scale_y_continuous(limits = c(0,2.461000)),
   variable == "humor" ~ scale_y_continuous(limits = c(0,1.609114)),
   variable == "social" ~ scale_y_continuous(limits = c(0,2.492847))
  )) +
  geom_point(alpha=0.15, size=1, shape=1) +
  geom_smooth(method="lm", size=0.5) +
  stat_cor(aes(label = ..r.label..), method = "pearson", digits = 3, show.legend = F, size = 2, label.x.npc = 0.75, label.y.npc = 0.25) +
  labs(x = "Model", y = "Human", color ="Model", fill = "Model") +
  scale_color_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  scale_fill_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  theme_bw() + 
  theme(legend.position = c(0.89,0.15),
        legend.key.size = unit(0.5, "cm"),
        strip.text.x = element_text(margin = margin(t = 2, b = 2)),
        strip.text = element_text(size = 8),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

# ggsave("figures/manuscript/exp1_sds.png", width = 7.29, height = 4.5)
```

```{r}
m2.1 <- lmer(z_scope ~ z_value + (1|word), data = exp1_sd_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))
summary(m2.1)
```

```{r}
m2.2_main <- lmer(z_scope ~ z_value + variable + (1|word), data = exp1_sd_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))
m2.2_intr <- lmer(z_scope ~ z_value * variable + (1|word), data = exp1_sd_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))

anova(m2.2_main, m2.2_intr)
```

```{r}
m2.3 <- lmer(z_scope ~ z_value * model + (1|word), data = exp1_sd_df %>% filter(variable %in% c("aoa", "arousal", "conc", "dom", "fam", "gender", "humor", "image", "size", "social", "valence")))
summary(m2.3)
```

# Exp 2.1

```{r}
lanc <- read_csv("data/manuscript/expt2msd/lanc.csv") %>%
  rename(word = Word) %>%
  pivot_longer(cols = !word, names_to = "variable", values_to = "value") %>%
  mutate(measure = case_when(endsWith(variable, ".mean") ~ "m", endsWith(variable, ".SD") ~ "sd"),
         variable = sub("\\.(mean|SD)$", "", variable),
         word = tolower(word)) %>%
  pivot_wider(names_from = measure, values_from = value) %>%
  mutate(source = "lanc")
```

```{r}
exp2_colnames <- c("source", "variable", "word", "n", "m", "sd")

gpt35a <- read_csv("data/manuscript/expt2msd/expt2Agpt35.csv", col_names = exp2_colnames)
gpt4a <- read_csv("data/manuscript/expt2msd/expt2Agpt4.csv", col_names = exp2_colnames)
gpt4oa <- read_csv("data/manuscript/expt2msd/expt2Agpt4o.csv", col_names = exp2_colnames)
gem15a <- read_csv("data/manuscript/expt2msd/expt2Agem15.csv", col_names = exp2_colnames)

gpt35p <- read_csv("data/manuscript/expt2msd/expt2Pgpt35.csv", col_names = exp2_colnames)
gpt4p <- read_csv("data/manuscript/expt2msd/expt2Pgpt4.csv", col_names = exp2_colnames)
gpt4op <- read_csv("data/manuscript/expt2msd/expt2Pgpt4o.csv", col_names = exp2_colnames)
gem15p <- read_csv("data/manuscript/expt2msd/expt2Pgem15.csv", col_names = exp2_colnames)

exp2_data <- rbind(gpt35a, gpt4a, gpt4oa, gem15a, gpt35p, gpt4p, gpt4op, gem15p) %>%
  mutate(variable = recode(variable,
                           "foot" = "Foot_leg",
                           "hand" = "Hand_arm",
                           "head" = "Head",
                           "mouth" = "Mouth",
                           "torso" = "Torso",
                           "hearing" = "Auditory",
                           "seeing" = "Visual",
                           "sensing" = "Interoceptive",
                           "smelling" = "Olfactory",
                           "tasting" = "Gustatory",
                           "touching" = "Haptic")) %>%
  select(!n)

exp2_data <- rbind(exp2_data, lanc)
```

## Means

```{r}
exp2_m_data <- exp2_data %>%
  select(!sd) %>%
  rename(value = m)
```

```{r}
lanc_data <- exp2_m_data %>%
  filter(source == "lanc") %>%
  rename("lanc" = value) %>%
  select(!source)

model_data <- exp2_m_data %>%
  filter(source != "lanc") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!source)

exp2_m_df <- left_join(model_data, lanc_data) %>%
  mutate(model = factor(model, levels = c("gpt35", "gpt4", "gpt4o", "gem15")),
         variable = factor(variable, levels = c("Auditory", "Gustatory", "Haptic", "Interoceptive",
                                                "Olfactory", "Visual", "Foot_leg", "Hand_arm", "Head",
                                                "Mouth", "Torso"))) %>%
  group_by(model, variable) %>%
  mutate(z_lanc = as.numeric(scale(lanc)),
         z_value = as.numeric(scale(value)))
```

```{r}
ggplot(exp2_m_df, aes(x=value, y=lanc, color=model, fill=model)) +
  facet_wrap(~variable, scales = "free") +
  ggh4x::facetted_pos_scales(
    x = list(
    variable == "Foot_leg" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Hand_arm" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Head" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Mouth" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Torso" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Auditory" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Gustatory" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Haptic" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Interoceptive" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Olfactory" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Visual" ~ scale_x_continuous(limits = c(0,5), n.breaks = 6)
  ), y = list(
    variable == "Foot_leg" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Hand_arm" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Head" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Mouth" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Torso" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Auditory" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Gustatory" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Haptic" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Interoceptive" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Olfactory" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6),
    variable == "Visual" ~ scale_y_continuous(limits = c(0,5), n.breaks = 6)
  )) +
  geom_point(alpha=0.15, size=1, shape=1) +
  geom_smooth(method="lm", size=0.5) +
  stat_cor(aes(label = ..r.label..), method = "pearson", digits = 2, show.legend = F, size = 2) +
  labs(x = "Model", y = "Human", color ="Model", fill = "Model") +
  scale_color_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  scale_fill_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  theme_bw() + 
  theme(legend.position = c(0.89,0.15),
        legend.key.size = unit(0.5, "cm"),
        strip.text.x = element_text(margin = margin(t = 2, b = 2)),
        strip.text = element_text(size = 8),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        # panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

# ggsave("figures/manuscript/exp2_means.png", width = 7.29, height = 4.5)
```

```{r}
# m3.1 <- lmer(lanc ~ value + (1|word), data = exp2_m_df)
# summary(m3.1)
```

```{r}
m3.2_main <- lmer(z_lanc ~ z_value + variable + (1|word), data = exp2_m_df)
m3.2_intr <- lmer(z_lanc ~ z_value * variable + (1|word), data = exp2_m_df)

anova(m3.2_main, m3.2_intr)
```

```{r}
m3.3 <- lmer(z_lanc ~ z_value * model + (1|word), data = exp2_m_df)
summary(m3.3)
```

```{r}
exp2_m_df <- exp2_m_df %>%
  mutate(type = case_when(
    variable %in% c("Auditory", "Gustatory", "Haptic", "Interoceptive", "Olfactory", "Visual") ~ "perceptual",
    TRUE ~ "motor"))

m3.4 <- lmer(z_lanc ~ z_value * type + (1|word), data = exp2_m_df)
summary(m3.4)
```

```{r}
exp2_m_df$variable <- relevel(factor(exp2_m_df$variable), ref = "Gustatory")

m3.5 <- lmer(z_lanc ~ z_value * variable + (1|word), data = exp2_m_df %>% filter(type == "perceptual"))
summary(m3.5)
```

## SDs

```{r}
exp2_sd_data <- exp2_data %>%
  select(!m) %>%
  rename(value = sd)
```

```{r}
lanc_data <- exp2_sd_data %>%
  filter(source == "lanc") %>%
  rename("lanc" = value) %>%
  select(!source)

model_data <- exp2_sd_data %>%
  filter(source != "lanc") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!source)

exp2_sd_df <- left_join(model_data, lanc_data) %>%
  mutate(model = factor(model, levels = c("gpt35", "gpt4", "gpt4o", "gem15")),
         variable = factor(variable, levels = c("Auditory", "Gustatory", "Haptic", "Interoceptive",
                                                "Olfactory", "Visual", "Foot_leg", "Hand_arm", "Head",
                                                "Mouth", "Torso"))) %>%
  group_by(model, variable) %>%
  mutate(z_lanc = as.numeric(scale(lanc)),
         z_value = as.numeric(scale(value)))
```

```{r}
sd_limits_max <- exp2_sd_df %>%
  group_by(variable) %>%
  summarize(max_lanc = max(lanc), max_value = max(value), min_lanc = min(lanc), min_value = min(value)) %>%
  group_by(variable) %>%
  summarize(max = max(max_lanc, max_value), min = min(min_lanc, min_value))

ggplot(exp2_sd_df, aes(x=value, y=lanc, color=model, fill=model)) +
  facet_wrap(~variable, scales = "free") +
  ggh4x::facetted_pos_scales(
    x = list(
    variable == "Foot_leg" ~ scale_x_continuous(limits = c(0,2.312936)),
    variable == "Hand_arm" ~ scale_x_continuous(limits = c(0,2.394438)),
    variable == "Head" ~ scale_x_continuous(limits = c(0,2.469818)),
    variable == "Mouth" ~ scale_x_continuous(limits = c(0,2.581989)),
    variable == "Torso" ~ scale_x_continuous(limits = c(0,2.422323)),
    variable == "Auditory" ~ scale_x_continuous(limits = c(0,2.378141)),
    variable == "Gustatory" ~ scale_x_continuous(limits = c(0,2.284861)),
    variable == "Haptic" ~ scale_x_continuous(limits = c(0,2.250926)),
    variable == "Interoceptive" ~ scale_x_continuous(limits = c(0,2.294014)),
    variable == "Olfactory" ~ scale_x_continuous(limits = c(0,2.342089)),
    variable == "Visual" ~ scale_x_continuous(limits = c(0,2.390955))
  ), y = list(
    variable == "Foot_leg" ~ scale_y_continuous(limits = c(0,2.312936)),
    variable == "Hand_arm" ~ scale_y_continuous(limits = c(0,2.394438)),
    variable == "Head" ~ scale_y_continuous(limits = c(0,2.469818)),
    variable == "Mouth" ~ scale_y_continuous(limits = c(0,2.581989)),
    variable == "Torso" ~ scale_y_continuous(limits = c(0,2.422323)),
    variable == "Auditory" ~ scale_y_continuous(limits = c(0,2.378141)),
    variable == "Gustatory" ~ scale_y_continuous(limits = c(0,2.284861)),
    variable == "Haptic" ~ scale_y_continuous(limits = c(0,2.250926)),
    variable == "Interoceptive" ~ scale_y_continuous(limits = c(0,2.294014)),
    variable == "Olfactory" ~ scale_y_continuous(limits = c(0,2.342089)),
    variable == "Visual" ~ scale_y_continuous(limits = c(0,2.390955))
  )) +
  geom_point(alpha=0.15, size=1, shape=1) +
  geom_smooth(method="lm", size=0.5) +
  stat_cor(aes(label = ..r.label..), method = "pearson", digits = 2, show.legend = F, size = 2, label.x.npc = 0.75, label.y.npc = 0.25) +
  labs(x = "Model", y = "Human", color ="Model", fill = "Model") +
  scale_color_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  scale_fill_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  theme_bw() + 
  theme(legend.position = c(0.89,0.15),
        legend.key.size = unit(0.5, "cm"),
        strip.text.x = element_text(margin = margin(t = 2, b = 2)),
        strip.text = element_text(size = 8),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

# ggsave("figures/manuscript/exp2_sds.png", width = 7.29, height = 4.5)
```

```{r}
m4.1 <- lmer(z_lanc ~ z_value + (1|word), data = exp2_sd_df)
summary(m4.1)
```

```{r}
m4.2_main <- lmer(z_lanc ~ z_value + variable + (1|word), data = exp2_sd_df)
m4.2_intr <- lmer(z_lanc ~ z_value * variable + (1|word), data = exp2_sd_df)

anova(m4.2_main, m4.2_intr)
```

```{r}
m4.3 <- lmer(z_lanc ~ z_value * model + (1|word), data = exp2_sd_df)
summary(m4.3)
```

```{r}
exp2_sd_df <- exp2_sd_df %>%
  mutate(type = case_when(
    variable %in% c("Auditory", "Gustatory", "Haptic", "Interoceptive", "Olfactory", "Visual") ~ "perceptual",
    TRUE ~ "motor"))

m4.4 <- lmer(z_lanc ~ z_value * type + (1|word), data = exp2_sd_df)
summary(m4.4)
```

# Exp 2.2: context manipulation

```{r}
gpt35abin <- read_csv("data/manuscript/expt2msd/expt2Agpt35bin.csv", col_names = exp2_colnames)
gpt4abin <- read_csv("data/manuscript/expt2msd/expt2Agpt4bin.csv", col_names = exp2_colnames)
gpt4oabin <- read_csv("data/manuscript/expt2msd/expt2Agpt4obin.csv", col_names = exp2_colnames)
gem15abin <- read_csv("data/manuscript/expt2msd/expt2Agem15bin.csv", col_names = exp2_colnames)

gpt35pbin <- read_csv("data/manuscript/expt2msd/expt2Pgpt35bin.csv", col_names = exp2_colnames)
gpt4pbin <- read_csv("data/manuscript/expt2msd/expt2Pgpt4bin.csv", col_names = exp2_colnames)
gpt4opbin <- read_csv("data/manuscript/expt2msd/expt2Pgpt4obin.csv", col_names = exp2_colnames)
gem15pbin <- read_csv("data/manuscript/expt2msd/expt2Pgem15bin.csv", col_names = exp2_colnames)

exp2_bindata <- rbind(gpt35abin, gpt4abin, gpt4oabin, gem15abin, gpt35pbin, gpt4pbin, gpt4opbin, gem15pbin) %>%
  mutate(variable = recode(variable,
                           "foot" = "Foot_leg",
                           "hand" = "Hand_arm",
                           "head" = "Head",
                           "mouth" = "Mouth",
                           "torso" = "Torso",
                           "hearing" = "Auditory",
                           "seeing" = "Visual",
                           "sensing" = "Interoceptive",
                           "smelling" = "Olfactory",
                           "tasting" = "Gustatory",
                           "touching" = "Haptic")) %>%
  select(!n)
```

```{r}
exp2_m_bindata <- exp2_bindata %>%
  select(!sd) %>%
  rename(value = m)
```

```{r}
lanc_data <- exp2_m_data %>%
  filter(source == "lanc") %>%
  rename("lanc" = value) %>%
  select(!source)

binned_data <- exp2_m_bindata %>%
  filter(source != "lanc") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!source) %>%
  mutate(condition = "binned")

orig_data <- exp2_m_df %>%
  select(word, variable, value, model) %>%
  mutate(condition = "orig")

model_data <- rbind(binned_data, orig_data)

exp2_m_bindf <- left_join(model_data, lanc_data) %>%
  filter(variable %in% c("Visual", "Mouth")) %>%
  mutate(variable = factor(variable, levels = c("Visual", "Mouth")),
         condition = factor(condition, levels = c("orig", "binned")))
```

```{r}
exp2_sd_bindata <- exp2_bindata %>%
  select(!m) %>%
  rename(value = sd)
```

```{r}
lanc_data <- exp2_sd_data %>%
  filter(source == "lanc") %>%
  rename("lanc" = value) %>%
  select(!source)

binned_data <- exp2_sd_bindata %>%
  filter(source != "lanc") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!source) %>%
  mutate(condition = "binned")

orig_data <- exp2_sd_df %>%
  select(word, variable, value, model) %>%
  mutate(condition = "orig")

model_data <- rbind(binned_data, orig_data)

exp2_sd_bindf <- left_join(model_data, lanc_data) %>%
  filter(variable %in% c("Visual", "Mouth")) %>%
  mutate(variable = factor(variable, levels = c("Visual", "Mouth")),
         condition = factor(condition, levels = c("orig", "binned")))
```

```{r}
exp2_m_bindf$measure <- "m"
exp2_sd_bindf$measure <- "sd"

exp2_bindf <- rbind(exp2_m_bindf, exp2_sd_bindf) %>%
  mutate(measure = factor(measure, levels = c("m", "sd"))) %>%
  group_by(measure, variable, model, condition) %>%
  mutate(z_lanc = as.numeric(scale(lanc)),
         z_value = as.numeric(scale(value)),
         model = factor(model, levels = c("gpt35", "gpt4", "gpt4o", "gem15")))
```

```{r}
# facet_labels_meas <- c(
#   "m" = "Mean",
#   "sd" = "SD"
# )
# 
# ggplot(exp2_bindf, aes(x=z_value, y=z_lanc, color=model, fill=model, linetype=condition)) +
#   facet_grid(measure ~ variable, labeller = labeller(measure = facet_labels_meas), scales = "free") +
#   geom_point(alpha=0.3, size=1, shape=1) +
#   geom_smooth(method="lm", size=0.5,) +
#   stat_cor(aes(label = ..r.label..), method = "pearson", digits = 2, show.legend = F, size = 3, label.x.npc = 0.75) +
#   labs(x = "Model", y = "Human", color = "Model", fill = "Model", linetype = "Condition") +
#   scale_color_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
#   scale_fill_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
#   scale_linetype_discrete(labels = c("orig" = "Original", "binned" = "Binned")) +
#   theme_bw() + 
#   theme(panel.grid.minor = element_blank())
# 
# ggsave("figures/manuscript/exp2_binned.png", width = 7.29, height = 4.5)
```

```{r}
m4.5 <- lm(z_lanc ~ z_value * condition, data = exp2_bindf %>% filter(measure == "m", variable == "Visual"))
summary(m4.5)
```

```{r}
m4.6 <- lm(z_lanc ~ z_value * condition, data = exp2_bindf %>% filter(measure == "sd", variable == "Visual"))
summary(m4.6)
```

```{r}
m4.7 <- lm(z_lanc ~ z_value * condition, data = exp2_bindf %>% filter(measure == "m", variable == "Mouth"))
summary(m4.7)
```

```{r}
m4.8 <- lm(z_lanc ~ z_value * condition, data = exp2_bindf %>% filter(measure == "sd", variable == "Mouth"))
summary(m4.8)
```

# Exp 3

```{r}
expt3naming <- read_csv("data/manuscript/expt3msd/expt3naming.csv")

scope <- expt3naming %>%
  select(Word, Naming_RT_ELP, Naming_SD) %>%
  rename(word = Word,
         m = Naming_RT_ELP,
         sd = Naming_SD) %>%
  mutate(variable = "naming",
         source = "scope")
```


```{r}
exp3_colnames = c("source", "variable", "word", "n", "m", "sd")

gpt35 <- read_csv("data/manuscript/expt3msd/expt3gpt35.csv", col_names = exp3_colnames) %>% select(!n)
gpt4 <- read_csv("data/manuscript/expt3msd/expt3gpt4.csv", col_names = exp3_colnames) %>% select(!n)
gpt4o <- read_csv("data/manuscript/expt3msd/expt3gpt4o.csv", col_names = exp3_colnames) %>% select(!n)
gem15 <- read_csv("data/manuscript/expt3msd/expt3gem15.csv", col_names = exp3_colnames) %>% select(!n)

exp3_data <- rbind(scope, gpt35, gpt4, gpt4o, gem15) %>%
  pivot_longer(cols = c(m, sd), names_to = "measure", values_to = "value")
```

```{r}
scope_data <- exp3_data %>%
  filter(source == "scope") %>%
  rename(scope = value) %>%
  select(!c(source))

model_data <- exp3_data %>%
  filter(source != "scope") %>%
  mutate(model = source) %>%
  mutate(model = factor(model)) %>%
  select(!c(source))

exp3_df <- left_join(model_data, scope_data) %>%
  mutate(model = factor(model, levels = c("gpt35", "gpt4", "gpt4o", "gem15"))) %>%
  group_by(model, measure, variable) %>%
  mutate(z_scope = as.numeric(scale(scope)),
         z_value = as.numeric(scale(value)))
```

```{r}
facet_labels <- c(
  "m" = "Mean",
  "sd" = "SD"
)

exp3_limits <- exp3_df %>%
  group_by(measure) %>%
  summarize(max_scope = max(scope), max_value = max(value), min_scope = min(scope), min_value = min(value))

ggplot(exp3_df, aes(x=value, y=scope, color=model, fill=model)) +
  facet_wrap(~measure, labeller = labeller(measure = facet_labels), scales = "free") +
  ggh4x::facetted_pos_scales(
    x = list(
    measure == "m" ~ scale_x_continuous(limits = c(282,851.542), n.breaks = 7),
    measure == "sd" ~ scale_x_continuous(limits = c(23.11805,338.967), n.breaks = 7)
  ), y = list(
    measure == "m" ~ scale_y_continuous(limits = c(282,851.542), n.breaks = 7),
    measure == "sd" ~ scale_y_continuous(limits = c(23.11805,338.967), n.breaks = 7)
  )) +
  geom_point(alpha=0.15, size=1, shape=1) +
  geom_smooth(method="lm", size=0.5) +
  stat_cor(aes(label = ..r.label..), method = "pearson", digits = 2, show.legend = F, size = 3) +
  labs(x = "Model", y = "Human", color ="Model", fill = "Model") +
  scale_color_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  scale_fill_discrete(labels = c("gpt35" = "GPT-3.5", "gpt4" = "GPT-4", "gpt4o" = "GPT-4o", "gem15" = "Gemini")) +
  theme_bw() + 
  theme(legend.key.size = unit(0.5, "cm"),
        strip.text.x = element_text(margin = margin(t = 2, b = 2)),
        strip.text = element_text(size = 8),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
        )

# ggsave("figures/manuscript/exp3.png", width = 7.29, height = 3.5)
```

```{r}
m5.1 <- lm(z_scope ~ z_value, data = exp3_df %>% filter(measure == "m"))
summary(m5.1)
```

```{r}
m5.2 <- lm(z_scope ~ z_value, data = exp3_df %>% filter(measure == "sd"))
summary(m5.2)
```

## Predictors

```{r}
exp3_predictors <- expt3naming %>%
  select(!c(Naming_RT_ELP, Naming_SD)) %>%
  rename(word = Word)

exp3_m_data <- exp3_data %>%
  filter(measure == "m") %>%
  select(!c(measure, variable))
  
exp3_pred_df <- left_join(exp3_m_data, exp3_predictors) %>%
  group_by(source) %>%
  mutate(z_value = as.numeric(scale(value)),
         source = factor(source, levels = c("scope", "gpt35", "gpt4", "gpt4o", "gem15")))
```

```{r}
m5.3 <- lmer(z_value ~ Freq * source + (1|word), data = exp3_pred_df)
summary(m5.3)
```

```{r}
m5.4 <- lmer(z_value ~ NLett * source + (1|word), data = exp3_pred_df)
summary(m5.4)
```

```{r}
m5.5 <- lmer(z_value ~ Consistency_Type_FF_O * source + (1|word), data = exp3_pred_df)
summary(m5.5)
```

```{r}
m5.6 <- lmer(z_value ~ initphon * source + (1|word), data = exp3_pred_df)
summary(m5.6)
```

```{r}
exp3_predictors <- read.csv('data/manuscript/exp3_predictors.csv') %>%
  select(!source)
```

```{r}
model_data <- exp3_data %>%
  filter(measure == "m") %>%
  mutate(source = factor(source)) %>%
  select(!measure)

exp3_pred_df <- left_join(model_data, exp3_predictors) %>%
  mutate(source = factor(source, levels = c("scope", "gpt35", "gpt4", "gpt4o", "gem15"))) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  group_by(source) %>%
  mutate(z_freq = as.numeric(scale(freq)),
         z_nlett = as.numeric(scale(nlett)),
         z_ld = as.numeric(scale(ld)),
         z_nm = as.numeric(scale(nm)))
```

```{r}
m6.1 <- lmer(z_ld ~ z_freq * `source` + z_nlett * `source` + (1|word), data = exp3_pred_df)
summary(m6.1)
```

```{r}
m6.2 <- lmer(z_nm ~ z_freq * `source` + z_nlett * `source` + (1|word), data = exp3_pred_df)
summary(m6.2)
```


